import { shallow } from 'enzyme';
import React, { Component } from 'react';
import ErrorBoundry from './ErrorBoundry';

it('is expected to render the ErrorBoundry component', () => {
  expect(shallow(<ErrorBoundry />)).toMatchSnapshot();
});

const ChildComponent = () => {<div></div>};

it('renders correctly when child has no error', () => {
  const wrapper = shallow(
    <ErrorBoundry >
      <ChildComponent />
    </ErrorBoundry>
    )
  expect(wrapper.state().hasError).toBe(false)
})

it('displays an error message on error generated by child', () => {
  const wrapper = shallow(
    <ErrorBoundry >
      <ChildComponent />
    </ErrorBoundry>
    )
  wrapper.instance().componentDidCatch('error')
  wrapper.update()
  expect(wrapper.state().hasError).toBe(true)
})